name: chartgeany
title: ChartGeany
version: 6.1.6-1snap
summary: Technical analysis software
description: |
 Technical analysis software for stocks and other 
 financial instruments. With 18 technical indicators, 
 portfolio manager for multiple portfolios and multiple currencies, 
 stock ticker, various drawing objects, easy download of quotes from 
 the net, periodical price updates and many more.
icon: chartgeany.png
license: GPL-2.0
architectures:
- build-on: amd64
  run-on: amd64
grade: stable
confinement: strict
base: core18

apps:
  chartgeany:
    command: bin/desktop-launch $SNAP/opt/chartgeany/ChartGeany
    desktop: usr/share/applications/chartgeany.desktop
    plugs: [x11, wayland, network, network-bind, home, desktop, desktop-legacy]

parts:
  chartgeany:
    plugin: qmake
    qt-version: qt4
    source: chartgeany-6.1.6.tar
    source-type: tar
    after: [desktop-qt4]

    build-packages:
      - libqtwebkit-dev
      - libqt4-dev
      - qt4-qmake
      - g++
    
    stage-packages: 
      - libqt4-network
      - libqt4-dbus
      - libqtwebkit4
      - libxcomposite1
      - libxcursor1
      
  desktop-qt4:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt4"]
    build-packages:
      - libqt4-dev
      - dpkg-dev
      - g++
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqtgui4
      - libgdk-pixbuf2.0-0
      - libqt4-svg # for loading icon themes which are svg
      - appmenu-qt
      - locales-all
      - sni-qt
      - libgtk2.0-0
   
  
